import { TrainingPlan } from '@/types';

const days = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"];

const createDailyWorkout = (day: number, activity: string, type: 'run' | 'strength' | 'rest'): { day: number, dayName: string, activity: string, type: 'run' | 'strength' | 'rest' } => ({
  day,
  dayName: days[day - 1],
  activity,
  type
});

export const TRAINING_PLANS: TrainingPlan[] = [
  {
    id: 'plan8',
    name: '8 Semanas',
    duration: 8,
    description: 'Para quem já possui algum nível de condicionamento e deseja evoluir de forma estruturada.',
    schedule: [
      { week: 1, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 8x(1 min corrida leve / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento + 8x(1 min corrida leve / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento + 8x(1 min corrida leve / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento + 8x(1 min corrida leve / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(7, '5 min aquecimento + 10x(1 min corrida leve / 2 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 2, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 7x(2 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento + 7x(2 min 30 seg corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento + 7x(3 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento + 7x(3 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(7, '5 min aquecimento + 10x(3 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 3, workouts: [
        createDailyWorkout(1, 'Aquecimento: 5 min Treino: 6x (4 min corrida leve / 1 min 30 seg caminhada) Desaquecimento: 5 min', 'run'),
        createDailyWorkout(2, 'Aquecimento: 5 min Treino: 6x (5 min corrida leve / 1 min 30 seg caminhada) Desaquecimento: 5 min', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, 'Aquecimento: 5 min Treino: 6x (6 min corrida leve / 1 min 30 seg caminhada) Desaquecimento: 5 min', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, 'Aquecimento: 5 min Treino: 6x (6 min corrida leve / 1 min 30 seg caminhada) Desaquecimento: 5 min', 'run'),
        createDailyWorkout(7, 'Aquecimento: 5 min Treino: 7x (6 min corrida leve / 1 min 30 seg caminhada) Desaquecimento: 5 min', 'run'),
      ]},
      { week: 4, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 4x(7 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento + 4x(7 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento + 4x(8 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento + 4x(8 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(7, '5 min aquecimento + 5x(8 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 5, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 3x(9 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento + 3x(10 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento + 3x(11 min corrida leve / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento + 3x(11 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(7, '5 min aquecimento + 4x(11 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 6, workouts: [
        createDailyWorkout(1, '5 min aquecimento, 3x(11 min corrida leve / 30 seg caminhada), 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento, 3x(13 min corrida leve / 1 min caminhada), 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento, 3x(14 min corrida leve / 1 min caminhada), 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento, 3x(15 min corrida leve / 1 min caminhada), 5 min desaquecimento', 'run'),
        createDailyWorkout(7, '5 min aquecimento, 3x(15 min corrida leve / 30 seg caminhada), 5 min desaquecimento', 'run'),
      ]},
      { week: 7, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 2x(17 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento + 2x(18 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento + 2x(19 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento + 2x(19 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(7, '5 min aquecimento + 2x(20 min corrida leve / 1 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 8, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 1x(24 min corrida leve) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, '5 min aquecimento + 1x(26 min corrida leve) + 5 min desaquecimento', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '5 min aquecimento + 1x(28 min corrida leve) + 5 min desaquecimento', 'run'),
        createDailyWorkout(5, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(6, '5 min aquecimento + 1x(30 min corrida leve) + 5 min desaquecimento', 'run'),
        createDailyWorkout(7, 'Objetivo Final: 5 min aquecimento + Corrida contínua de 5 km SEM PAUSAS', 'run'),
      ]},
    ],
  },
  {
    id: 'plan12',
    name: '12 Semanas',
    duration: 12,
    description: 'Progressão gradual para quem busca consistência e evolução segura.',
    schedule: [
      { week: 1, workouts: [
        createDailyWorkout(1, '20 minutos de caminhada em ritmo moderado', 'run'),
        createDailyWorkout(2, '25 minutos de caminhada em ritmo moderado', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '30 minutos de caminhada em ritmo moderado', 'run'),
        createDailyWorkout(5, '30 minutos de caminhada em ritmo moderado', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '40 minutos de caminhada em ritmo moderado', 'run'),
      ]},
      { week: 2, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 4x(30 seg corrida / 2 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 4x(30 seg corrida / 2 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 4x(30 seg corrida / 2 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 5x(45 seg corrida / 2 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
      ]},
       { week: 3, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 5x(1 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 5x(1 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 5x(1 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 6x(1 min 30 seg corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 4, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 5x(2 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 5x(2 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 5x(2 min 30 seg corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 6x(2 min 30 seg corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 5, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 5x(3 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 5x(3 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 5x(3 min 30 seg corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 6x(4 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 6, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 5x(4 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 5x(4 min 30 seg corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 5x(4 min 30 seg corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 6x(5 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 7, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 5x(5 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 5x(5 min corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 5x(5 min 30 seg corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 6x(6 min corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 8, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 4x(7 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 4x(7 min 30 seg corrida / 1 min 15 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 4x(7 min 30 seg corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 5x(8 min corrida / 1 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 9, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 4x(8 min corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 4x(8 min corrida / 45 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 4x(8 min 30 seg corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 5x(9 min corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 10, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 3x(10 min corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 3x(10 min corrida / 45 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 3x(10 min corrida / 45 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 4x(10 min corrida / 30 seg caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 11, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 3x(11 min corrida / 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 3x(12 min corrida / 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 3x(13 min corrida / 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 4x(15 min corrida / 1 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      { week: 12, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 3x(16 min corrida / 45 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 2x(18 min corrida / 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 2x(20 min corrida / 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, 'Objetivo Final: 5 min aquecimento + Corrida contínua de 5 km SEM PAUSAS', 'run'),
      ]},
    ],
  },
   {
    id: 'plan16',
    name: '16 Semanas',
    duration: 16,
    description: 'Para iniciantes ou quem prefere uma progressão mais leve e gradual.',
    schedule: [
      { week: 1, workouts: [
        createDailyWorkout(1, '20 min caminhada confortável', 'run'),
        createDailyWorkout(2, '25 min caminhada confortável', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '30 min caminhada confortável', 'run'),
        createDailyWorkout(5, '30 min caminhada confortável', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '35 min caminhada confortável', 'run'),
      ]},
      { week: 2, workouts: [
        createDailyWorkout(1, '40 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(2, '40 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(3, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(4, '45 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(5, '50 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '60 min caminhada confortável/acelerada', 'run'),
      ]},
      { week: 3, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 8x(30 seg corrida / 2 min 30 seg caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 10x(30 seg corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 10x(45 seg corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 10x(1 min corrida / 2 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      // ... Add all other weeks for 16-week plan
      ...Array.from({ length: 13 }, (_, i) => i + 4).map(weekNum => ({
        week: weekNum,
        workouts: [
          createDailyWorkout(1, `Treino Semana ${weekNum}`, 'run'),
          createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
          createDailyWorkout(3, `Treino Semana ${weekNum}`, 'run'),
          createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
          createDailyWorkout(5, `Treino Semana ${weekNum}`, 'run'),
          createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
          createDailyWorkout(7, `Treino Longo Semana ${weekNum}`, 'run'),
        ]
      }))
    ]
  },
  {
    id: 'plan20',
    name: '20 Semanas',
    duration: 20,
    description: 'Adaptação mais gradual para quem não pratica atividades físicas regularmente.',
    schedule: [
       { week: 1, workouts: [
        createDailyWorkout(1, '20 min caminhada confortável', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '30 min caminhada confortável', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '35 min caminhada confortável', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '40 min caminhada confortável', 'run'),
      ]},
      { week: 2, workouts: [
        createDailyWorkout(1, '45 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '50 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '55 min caminhada confortável/acelerada', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '60 min caminhada confortável/acelerada', 'run'),
      ]},
       { week: 3, workouts: [
        createDailyWorkout(1, '5 min aquecimento + 6x(30 seg corrida / 4 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(3, '5 min aquecimento + 6x(30 seg corrida / 4 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(5, '5 min aquecimento + 7x(30 seg corrida / 4 min caminhada) + 5 min desaquecimento', 'run'),
        createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
        createDailyWorkout(7, '5 min aquecimento + 8x(30 seg corrida / 4 min caminhada) + 5 min desaquecimento', 'run'),
      ]},
      // ... Add all other weeks for 20-week plan
      ...Array.from({ length: 17 }, (_, i) => i + 4).map(weekNum => ({
        week: weekNum,
        workouts: [
          createDailyWorkout(1, `Treino Semana ${weekNum}`, 'run'),
          createDailyWorkout(2, 'Descanso/Fortalecimento', 'strength'),
          createDailyWorkout(3, `Treino Semana ${weekNum}`, 'run'),
          createDailyWorkout(4, 'Descanso/Fortalecimento', 'strength'),
          createDailyWorkout(5, `Treino Semana ${weekNum}`, 'run'),
          createDailyWorkout(6, 'Descanso/Fortalecimento', 'strength'),
          createDailyWorkout(7, `Treino Longo Semana ${weekNum}`, 'run'),
        ]
      }))
    ]
  }
];
